services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    privileged: true
    user: root
  #   volumes:
  #     - ./backend:/app
  #   # depends_on:
  #   #   - db
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:8080"
    # volumes:
    #   - ./frontend:/app
    # stdin_open: true
    # tty: true
    # depends_on:
    #   - backend
